Products/urls.py
from django.urls import path, include
from .views import CategoryDetailView, ProductDetailView, like_comment, create_comment

urlpatterns = [
    path('category/<slug:category_slug>', CategoryDetailView.as_view(), name='category_detail'),
    # path('product/<slug:product_slug>/', ProductDetailView.as_view(), name='product_detail'),
    path('product/<slug:product_slug>/<slug:shop_slug>/', ProductDetailView.as_view(), name='product_detail'),
    path('like_comment/', like_comment, name='like_comment'),
    path('comments/', create_comment, name='add_comment'),
]

mysite/urls.py
from django.contrib import admin
from django.conf import settings
# from mysite import settings
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include("siteview.urls")),
                  path('products/', include("Products.urls")),
                  path('accounts/', include('Accounts.urls'))
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL,
                                                                                           document_root=settings.MEDIA_ROOT)

Products/models.py
from django.contrib.contenttypes.fields import GenericRelation
from django.db import models
from django.db.models.base import Model
from django.utils.translation import ugettext_lazy as _
from django.conf import settings
from Accounts.models import Shop
from django.urls import reverse


# Create your models here.


class Category(models.Model):
    name = models.CharField(_('name'), max_length=50)
    slug = models.SlugField(_('slug'), unique=True)
    detail = models.TextField(_('detail'))
    image = models.ImageField(_('image'), upload_to='Product/Category/image')
    parent = models.ForeignKey(
        'self', verbose_name=_("Parent"), on_delete=models.SET_NULL, null=True, blank=True,
        related_name='children', related_query_name='children')

    class Meta:
        verbose_name = _('Category')
        verbose_name_plural = _('Categories')

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('category_detail', kwargs={'category_slug': self.slug})


class Brand(models.Model):
    name = models.CharField(_('name'), max_length=50)
    detail = models.TextField(_('detail'))
    image = models.ImageField(_('image'), upload_to='Product/Brand/image')

    class Meta:
        verbose_name = _('Brand')
        verbose_name_plural = _('Brands')

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(_('name'), max_length=50)
    slug = models.SlugField(_('slug'), unique=True)
    detail = models.TextField(_('detail'))
    image = models.ImageField(_('image'), upload_to='Product/Product/image')
    brand = models.ForeignKey(Brand, related_name='Product', related_query_name='Product', verbose_name=_(
        "brand"), on_delete=models.CASCADE)
    category = models.ForeignKey(Category, related_name='products', verbose_name=_(
        "Category"), on_delete=models.SET_NULL, null=True, blank=True)
    seen = models.IntegerField(_('seen'), default=0)

    class Meta:
        verbose_name = _('Product')
        verbose_name_plural = _('Products')

    def __str__(self):
        return self.name



class ProductMeta(models.Model):
    product = models.ForeignKey(Product, related_name='ProductMeta', related_query_name='ProductMeta',
                                verbose_name=_("Product"), on_delete=models.CASCADE)
    label = models.CharField(_('label'), max_length=50)
    value = models.IntegerField(_('value'))

    class Meta:
        verbose_name = _('ProductMeta')
        verbose_name_plural = _('ProductMetas')

    def __str__(self):
        return self.product.name


class Image(models.Model):
    product = models.ForeignKey(Product, related_name='Images', related_query_name='Images', verbose_name=_(
        "Product"), on_delete=models.CASCADE)
    image = models.ImageField(_('image'), upload_to='Product/Image/image')

    class Meta:
        verbose_name = _('Image')
        verbose_name_plural = _('Images')

    def __str__(self):
        return self.product.name


class Comment(models.Model):
    content = models.TextField(_("Content"))
    product = models.ForeignKey(Product, related_name='comments', related_query_name='comments', verbose_name=_(
        "Product"), on_delete=models.CASCADE)
    create_at = models.DateTimeField(_("Create at"), auto_now_add=True)
    update_at = models.DateTimeField(_("Update at"), auto_now=True)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name=_(
        "Author"), on_delete=models.CASCADE)
    is_confirmed = models.BooleanField(_("confirm"), default=True)

    class Meta:
        verbose_name = _("Comment")
        verbose_name_plural = _("Comments")
        ordering = ['-create_at']

    def __str__(self):
        return self.product.name

    @property
    def like_count(self):
        q = like.objects.filter(comment=self,condition=True)
        return q.count()

    @property
    def dislike_count(self):
        q = like.objects.filter(comment=self,condition=False)
        return q.count()





class ShopProduct(models.Model):
    shop = models.ForeignKey(Shop, related_name='Shops', related_query_name='Shops', verbose_name=_(
        "Shops"), on_delete=models.CASCADE)
    product = models.ForeignKey(Product, related_name='ShopProducts', related_query_name='ShopProducts', verbose_name=_(
        "ShopProduct"), on_delete=models.CASCADE)
    price = models.FloatField(_('price'))
    quantity = models.IntegerField(_('quantity'))

    def save(self, *args, **kwargs):
        self.full_clean()
        super().save(*args, **kwargs)

    class Meta:
        verbose_name = _('ShopProduct')
        verbose_name_plural = _('ShopProducts')
        unique_together = [('shop', 'product')]

    def __str__(self):
        return self.shop.name

    def incrementViewCount(self):
        self.product.seen += 1
        self.product.save()
        return self.product.seen


    def get_absolute_url(self):
        return reverse('product_detail', kwargs={'product_slug': self.product.slug , 'shop_slug': self.shop.slug})



class like(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='userlikes', related_query_name='userlikes',
                             verbose_name=_(
                                 "user"), on_delete=models.SET_NULL, null=True)

    comment = models.ForeignKey(Comment, related_name='comment_likes', related_query_name='comment_likes', verbose_name=_(
        "comment"), on_delete=models.CASCADE)

    condition = models.BooleanField(_('condition'))


    class Meta:
        verbose_name = _('like')
        verbose_name_plural = _('likes')

    def __str__(self):
        return self.user.mobile

Products/forms.py
from django import forms
from django.utils.translation import ugettext_lazy as _
from Products.models import Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('content',)
        labels = {'content': _("Comment"), }
        widgets = {'content': forms.Textarea(attrs={'cols': 100, 'rows': 5})}

Products/views.py
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import TemplateView, ListView, DetailView

from Products.forms import CommentForm
from Products.models import Product, ShopProduct, Comment, like
from Products.models import Category
import json


# Create your views here.


class ProductDetailView(DetailView):
    model = ShopProduct
    template_name = 'product.html'
    context_object_name = 'product'
    slug_url_kwarg = 'product_slug'

    def get_object(self):
        slug1 = self.kwargs.get('product_slug')
        slug2 = self.kwargs.get('shop_slug')
        item = get_object_or_404(ShopProduct, product__slug=slug1, shop__slug=slug2)
        item.incrementViewCount()
        return item

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["categories"] = Category.objects.all()
        context["comments"] = Comment.objects.all()
        context['form'] = CommentForm()
        return context


class CategoryDetailView(ListView):
    model = Category
    template_name = 'category.html'
    paginate_by = 9

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        slug = self.kwargs.get('category_slug')
        category = get_object_or_404(Category.objects.filter(), slug=slug)
        # context["products"] = Product.objects.filter(category=category)
        context["shopproducts"] = ShopProduct.objects.filter(product__category=category)
        context["categories"] = Category.objects.all()
        return context


@csrf_exempt
def like_comment(request):
    data = json.loads(request.body)
    user = request.user
    try:
        comment = Comment.objects.get(id=data['comment_id'])
    except Comment.DoesNotExist:
        return HttpResponse('bad request', status=404)
    try:
        comment_like = like.objects.get(user=user, comment=comment)
        comment_like.condition = data['condition']
        comment_like.save()
    except like.DoesNotExist:
        like.objects.create(user=user, condition=data['condition'], comment=comment)
    result = {'like_count': comment.like_count, 'dislike_count': comment.dislike_count}

    return HttpResponse(json.dumps(result), status=201)


@csrf_exempt
def create_comment(request):
    data = json.loads(request.body)
    user = request.user
    try:
        comment = Comment.objects.create(product_id=data['product_id'], content=data['content'], author=user)
        result = {"comment_id": comment.id, "content": comment.content, 'dislike_count': 0, 'like_count': 0,
                  'full_name': user.email}
        return HttpResponse(json.dumps(result), status=201)
    except:
        result = {"error": 'error'}
        return HttpResponse(json.dumps(result), status=400)

templates/category.html
{% extends 'base/base.html' %}
{% load static %}

{% block title %} Category {% endblock %}
{% block content %}
    <!-- Start Top Search -->
    <div class="top-search">
        <div class="container">
            <div class="input-group">
                <span class="input-group-addon"><i class="fa fa-search"></i></span>
                <input type="text" class="form-control" placeholder="Search">
                <span class="input-group-addon close-search"><i class="fa fa-times"></i></span>
            </div>
        </div>
    </div>
    <!-- End Top Search -->



    <!-- Start Shop Page  -->
    <div class="shop-box-inner">
        <div class="container">
            <div class="row">
                <div class="col-xl-3 col-lg-3 col-sm-12 col-xs-12 sidebar-shop-left">
                    <div class="product-categori">
                        <div class="search-product">
                            <form action="#">
                                <input class="form-control" placeholder="Search here..." type="text">
                                <button type="submit"><i class="fa fa-search"></i></button>
                            </form>
                        </div>


                        <div class="filter-sidebar-left">
                            <div class="title-left">
                                <h3>Categories</h3>
                            </div>
                            <div class="list-group list-group-collapse list-group-sm list-group-tree"
                                 id="list-group-men">

                                {% for cat in categories %}
                                <div class="dropright">
                                {% if cat.parent == None %}
                                    
                                    <a href="{{ cat.get_absolute_url }}" class="dropdown-toggle"  id="dropdownMenu2" data-toggle="dropdown"
                                       aria-haspopup="true" aria-expanded="false">
                                        {{ cat.name }}
                                    </a>
                                    {% endif %}

                                    <div class="dropdown-menu" aria-labelledby="dropdownMenu2">
                                        {% for incat in categories %}
                                            {% if incat.parent == cat %}
                                        <a href="{{ incat.get_absolute_url }}" class="dropdown-item" >{{ incat.name }}</a>
                                            {% endif %}
                                            {% endfor %}
                                    </div>
                                </div>
                                {% endfor %}

                            </div>
                        </div>


                        <div class="filter-brand-left">
                            <div class="title-left">
                                <h3>Brand</h3>
                            </div>
                            <div class="brand-box">
                                <ul>
                                    {% for brand in products %}
                                        {% ifchanged brand.brand %}
                                            <li>
                                                <div class="radio radio-danger">
                                                    <input name="survey" id="Radios1" value="Yes" type="radio">
                                                    <label for="Radios1"> {{ brand.brand }} </label>
                                                </div>
                                            </li>
                                        {% endifchanged %}
                                    {% endfor %}
                                </ul>
                            </div>
                        </div>


                    </div>
                </div>
                <div class="col-xl-9 col-lg-9 col-sm-12 col-xs-12 shop-content-right">
                    <div class="right-product-box">
                        <div class="product-item-filter row">
                            <div class="col-12 col-sm-8 text-center text-sm-left">
                                <div class="toolbar-sorter-right">
                                    <span>Sort by </span>
                                    <select id="basic" class="selectpicker show-tick form-control"
                                            data-placeholder="$ USD">
                                        <option data-display="Select">بدون فيلتر</option>
                                        <option value="1">محبوبيت</option>
                                        <option value="2">قيمت كم → قيمت زياد</option>
                                        <option value="3">قيمت زياد → قيمت كم</option>
                                        <option value="4">پرفروش ترين</option>
                                    </select>
                                </div>
                                <p>result: {{ products.count }} product</p>
                            </div>
                            <div class="col-12 col-sm-4 text-center text-sm-right">
                                <ul class="nav nav-tabs ml-auto">
                                    <li>
                                        <a class="nav-link active" href="#grid-view" data-toggle="tab"> <i
                                                class="fa fa-th"></i> </a>
                                    </li>
                                    <li>
                                        <a class="nav-link" href="#list-view" data-toggle="tab"> <i
                                                class="fa fa-list-ul"></i> </a>
                                    </li>
                                </ul>
                            </div>
                        </div>

                        <div class="row product-categorie-box">
                            <div class="tab-content">
                                <div role="tabpanel" class="tab-pane fade show active" id="grid-view">
                                    <div class="row">


                                        {% for cat in shopproducts %}
                                            <div class="col-sm-6 col-md-6 col-lg-4 col-xl-4">
                                                <div class="products-single fix">
                                                    <div class="box-img-hover">
                                                        <div class="type-lb">
                                                            <p class="sale">Sale</p>
                                                        </div>
                                                        <img src="{{ cat.product.image.url }}" class="img-fluid"
                                                             alt="Image">
                                                        <div class="mask-icon">
                                                            <ul>

                                                                <li><a href="#" data-toggle="tooltip"
                                                                       data-placement="right"
                                                                       title="Add to Wishlist"><i
                                                                        class="far fa-heart"></i></a>
                                                                </li>
                                                            </ul>
                                                            <a class="cart" href="#">Add to Cart</a>
                                                        </div>
                                                    </div>
                                                    <div class="why-text">
                                                        <a href="{{ cat.get_absolute_url }}">
                                                            <h4>{{ cat.product.name }}</h4></a>
                                                        <h5> {{ cat.price }}</h5>
                                                    </div>
                                                </div>
                                            </div>



                                        {% endfor %}


                                    </div>
                                </div>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- End Shop Page -->

{% endblock %}

templates/product.html
{% extends 'base/base.html' %}
{% load static %}

{% block title %} product {% endblock %}
{% block content %}

    <!-- Start Top Search -->
    <div class="top-search">
        <div class="container">
            <div class="input-group">
                <span class="input-group-addon"><i class="fa fa-search"></i></span>
                <input type="text" class="form-control" placeholder="Search">
                <span class="input-group-addon close-search"><i class="fa fa-times"></i></span>
            </div>
        </div>
    </div>
    <!-- End Top Search -->

    <div>
        <!-- Start Shop Detail  -->
        <div class="shop-detail-box-main">
            <div class="container">
                <div class="row">
                    <div class="col-xl-5 col-lg-5 col-md-6">
                        <div id="carousel-example-1" class="single-product-slider carousel slide" data-ride="carousel">
                            <div class="carousel-inner" role="listbox">
                                <div class="carousel-item active"><img class="d-block w-100"
                                                                       src="{{ product.product.image.url }}"
                                                                       alt="First slide"></div>
                                <div class="carousel-item"><img class="d-block w-100"
                                                                src="{{ product.product.image.url }}"
                                                                alt="Second slide"></div>
                                <div class="carousel-item"><img class="d-block w-100"
                                                                src="{{ product.product.image.url }}"
                                                                alt="Third slide"></div>
                            </div>
                            <a class="carousel-control-prev" href="#carousel-example-1" role="button" data-slide="prev">
                                <i class="fa fa-angle-left" aria-hidden="true"></i>
                                <span class="sr-only">Previous</span>
                            </a>
                            <a class="carousel-control-next" href="#carousel-example-1" role="button" data-slide="next">
                                <i class="fa fa-angle-right" aria-hidden="true"></i>
                                <span class="sr-only">Next</span>
                            </a>
                            <ol class="carousel-indicators">
                                <li data-target="#carousel-example-1" data-slide-to="0" class="active">
                                    <img class="d-block w-100 img-fluid" src="{{ product.product.image.url }}" alt=""/>
                                </li>
                                <li data-target="#carousel-example-1" data-slide-to="1">
                                    <img class="d-block w-100 img-fluid" src="{{ product.product.image.url }}" alt=""/>
                                </li>
                                <li data-target="#carousel-example-1" data-slide-to="2">
                                    <img class="d-block w-100 img-fluid" src="{{ product.product.image.url }}" alt=""/>
                                </li>
                            </ol>
                        </div>
                    </div>
                    <div class="col-xl-7 col-lg-7 col-md-6">
                        <div class="single-product-details">
                            <h2>{{ product.product.name }}</h2>
                            <h5>
                                <del>{{ product.price }}</del>
                                {{ product.price }}
                            </h5>
                            <p class="available-stock"><span> موجودی : {{ product.quantity }} / <a href="#">{{ 0 }} فروخته شده </a></span>
                            <p>
                            <h4>در مورد محصول:</h4>
                            <p>{{ product.product.detail|safe }}</p>

                            <div class="price-box-bar">
                                <div class="cart-and-bay-btn">
                                    <a class="btn hvr-hover" data-fancybox-close="" href="#">Add to cart</a>
                                </div>
                            </div>

                            <div class="add-to-btn">
                                <div class="add-comp">
                                    <a class="btn hvr-hover" href="#"><i class="fas fa-heart"></i> Add to wishlist</a>
                                </div>
                            </div>

                        </div>
                    </div>
                </div>

                <p> چندبار دیده شده:{{ product.product.seen }}</p>

            </div>
        </div>
        <!-- End Cart -->
        <hr>
        <div class="container" >
            <h2 class="text-right">مشخصات محصول</h2>
        </div>

        <hr>
        <div class="container d-flex">

            {% if request.user.is_authenticated %}

                <form id="comment_form">
                    {% csrf_token %}
                    {% include 'component/commentform.html' %}

                    <input type="submit" value="ok" class="btn btn-outline-info">
                </form>
            {% else %}
                <div class="col-lg-12 col-sm-6 mb-5">
                    <textarea class="form-control" rows="5" cols="100" readonly>برای ثبت نظر وارد شوید</textarea>
                </div>
            {% endif %}


        </div>

        <hr>
        <h2 class="text-center">بخش نظرات</h2>
        <hr>

        <div class="container adds">
            {% for comment in comments %}
                <div class="row mt-5 mb-5" style="border: #0c5460 solid">
                    <div class="container">
                        <h3>{{ comment.author }}</h3>
                        <p>{{ comment.content }}</p>
                    </div>


                    <div>
                        like:<span id='like_counter{{ comment.id }}'>{{ comment.like_count }}</span>
                        dislike:<span id='dislike_counter{{ comment.id }}'>{{ comment.dislike_count }}</span>
                    </div>
                    <div class="mx-5">
                        <button class="bg-success" onclick="likecomment({{ comment.id }})"></button>
                        <button class="bg-danger" onclick="likecomment({{ comment.id }},false)"></button>
                    </div>


                </div>
            {% endfor %}
        </div>


    </div>
{% endblock %}





{% block javascript %}


    <script>
        function likecomment(commentID, condition = true) {
            const data = JSON.stringify({comment_id: commentID, condition})
            console.log(data)
            $.ajax({
                type: "POST",
                url: "{% url 'like_comment' %}",
                data: data,
                success: function (response) {
                    console.log(response)
                    const data = JSON.parse(response)
                    $(`#like_counter${commentID}`).text(data.like_count)
                    $(`#dislike_counter${commentID}`).text(data.dislike_count)
                }
            });

        }
    </script>



    <script>
        document.getElementById("comment_form").addEventListener("submit", function (event) {
            event.preventDefault();
            const content = $('#id_content').val()
            const data = JSON.stringify({content, product_id:{{product.id}}})
            $.ajax({
                type: "post",
                url: "{% url 'add_comment' %}",
                data: data,
                success: function (response) {
                    const data = JSON.parse(response)
                    console.log(data)
                    const result = `
                                 <div class="row mt-5 mb-5" style="border: #0c5460 solid">
                    <div class="container">
                        <h3>${data.full_name}</h3>
                        <p>${data.content}</p>
                    </div>


                    <div>
                        like:<span id='like_counter${data.id}'>${data.like_count}</span>
                        dislike:<span id='dislike_counter${data.id}'>${data.dislike_count}</span>
                    </div>
                    <div class="mx-5">
                        <button class="bg-success" onclick="likecomment(${data.id})"></button>
                        <button class="bg-danger" onclick="likecomment(${data.id},false)"></button>
                    </div>


                </div>`
                    $(".adds").prepend(result);
                }
            });
        }, false);
    </script>
{% endblock %}